### ISSUE TITLE
Unable to type 6 digits colors

### ISSUE THREAD

**Issue by jacomyal** [mapbox/react-colorpickr#100]
When I try to type `123456` in the bottom right input, once `123` are typed, typing `4`, `5` and then `6` each modify the alpha channel instead of the actual color hex code.

At the end, my color is `#123` (with an alpha channel set by `6`) instead of a fully opaque `#123456`.

**Comment by tristen** [comment]
Just going to leave this here too (I think its related) https://twitter.com/MarcoPPino/status/933312166308057088 I'll prioritize fixing this soon 😬

**Comment by tristen** [comment]
Actually, this specific issue ^ doesn't appear to be reproducible on https://www.mapbox.com/react-colorpickr/ :/
