### ISSUE TITLE
React.PropTypes not compatible with React 16

### ISSUE THREAD

**Issue by aparlato** [mapbox/react-colorpickr#102]
`React.PropTypes` is not compatible with React 16 which no longer gives a warning about this being deprecated like 15, but actually errors on it.

This should be replaced with `prop-types` module.

https://github.com/mapbox/react-colorpickr/blob/mb-pages/dist/inputs/number-input.js#L32-L36
(appears in other places as well)

**Comment by M-ZubairAhmed** [comment]
can I take this issue , and work on migration to PropTypes package?

**Comment by tristen** [comment]
@M-ZubairAhmed that would be great!

**Comment by M-ZubairAhmed** [comment]
i have going through souce code it seems in folder `src` proptypes as a seperate package is already added. Should i continue to add it in files under `dist`?

**Comment by M-ZubairAhmed** [comment]
Please see [PR103](https://github.com/mapbox/react-colorpickr/pull/103) is this what you are looking for?
