### ISSUE TITLE
Layout adjustments to alpha slider and small style considerations

### ISSUE THREAD

**Issue by tristen** [mapbox/react-colorpickr#105]
@dasulit what do you think about moving the alpha slider vertically alongside the color ramp one and mirroring the keyline style of the radio group (like it is in Studio) here? Something like this:

<img width="279" alt="screen shot 2017-10-15 at 11 37 29 am" src="https://user-images.githubusercontent.com/61150/31586327-4a81d3dc-b19d-11e7-8f19-71773d085e95.png">

**Comment by dasulit** [comment]
This looks nice @tristen, I’d be enthusiastic about this change 👍
