### ISSUE TITLE
Cannot delete input value without adding a zero

### ISSUE THREAD

**Issue by davidtheclark** [mapbox/react-colorpickr#111]
![jan-09-2018 16-47-02](https://user-images.githubusercontent.com/628431/34749085-bff80b2e-f55c-11e7-90b2-f892429f55aa.gif)

When I delete, a `0` is added, which then gets in the way. I can't delete the zero and then add another number: to set it to `6`, for example, I'll need to end up with `06`. In the GIF above, I deleted, then hit `ctrl+z` to undo, and look at what happened to me! `(ಠ_ಠ)`

@tristen: Do you think it'd be feasible to use `0` as a *placeholder* instead of a real value in the input?

**Comment by tristen** [comment]
> @tristen: Do you think it'd be feasible to use `0` as a _placeholder_ instead of a real value in the input?

Hmm to do that I think we would need to change these inputs to `type="text"`.

**Comment by tristen** [comment]
I'm going to close this as the number input gives us proper min/max constraints we need 
and there are a few ways to replace the 0 with another value.

![deleting](https://user-images.githubusercontent.com/61150/41292328-380f2d04-6e20-11e8-8ca5-5e2d45fa99a1.gif)

**Comment by davidtheclark** [comment]
@tristen This behavior still seems problematic to me. If I have a zero in the input, I just can't delete it; so if I want to set the value to 6, I need the input to say 06, then I can delete the zero. That seems confusing and counterintuitive. If I have just 6 and I want to change it to 7, I hit delete and a 0 appears, then I run into the same confusion.

**Comment by tristen** [comment]
OK let's leave this open then

**Comment by tristen** [comment]
Inspired to change this after seeing https://technology.blog.gov.uk/2020/02/24/why-the-gov-uk-design-system-team-changed-the-input-type-for-numbers/
