### ISSUE TITLE
Add hex code

### ISSUE THREAD

**Issue by aparlato** [mapbox/react-colorpickr#112]
I think the minor addition of the hex code might make some workflows easier. 

When designing maps we often go back and forth between Studio and some other program like Illustrator. Illustrator to Studio we can copy a hex code, but once we edit this it becomes hsl or rgb and to return that adjusted color to Illustrator we need to either copy over the individual rgb values or screenshot and use the eyedropper tool. 

Displaying a hex code somewhere may make it a little easier to do this back and forth.

![image](https://user-images.githubusercontent.com/15698320/36554561-728aee68-17b4-11e8-972a-498dce03bbb0.png)

**Comment by dasulit** [comment]
@aparlato react-colorpickr does indeed support hex codes: see the example at https://www.mapbox.com/react-colorpickr/.
