### ISSUE TITLE
react-colorpickr should manage less state

### ISSUE THREAD

**Issue by tristen** [mapbox/react-colorpickr#113]
Right now react-colorpickr manages a few things in state that it doesn't necessarily need to. One is `value`. But value can also be passed as a prop. I wonder if the value of the colorpickr should _always_ be passed back to it as props? cc/ @davidtheclark if you had any thoughts on this.

**Comment by davidtheclark** [comment]
> I wonder if the value of the colorpickr should always be passed back to it as props?

I think that'd be a worthy breaking change — making this a controlled input, instead of an uncontrolled one.
