### ISSUE TITLE
could not complier

### ISSUE THREAD

**Issue by tiansijie** [mapbox/react-colorpickr#13]
react-colorpickr/index.js Line 206: Unexpected token <
You may need an appropriate loader to handle this file type.

```
return (
/* jshint ignore:start */
<div className='colorpickr' onClick={this._onClick}>
<div className='colorpickr-body'>
<div className='col'>
```

**Comment by tiansijie** [comment]
Doesn't work with the webpack build. looks like babelify is not in the dependencies

**Comment by tristen** [comment]
@tiansijie Babelify is under `devDependencies` in [package.json](https://github.com/mapbox/react-colorpickr/blob/0fb25f535db67ca1df930a4d4bae3f47b376480b/package.json#L33). Is that causing the issue or is there a flag you can set in webpack to pick up these dev dependencies?
