### ISSUE TITLE
Errors when updating color

### ISSUE THREAD

**Issue by wangzuo** [mapbox/react-colorpickr#14]
One thing to notice is that rgb colors and hsv colors are not 1-1 mapping, so hsv -> rgb -> hsv may not return the original hsv value. Thats why i [check](https://github.com/wangzuo/react-input-color/blob/master/lib/input-color.js#L76) whether the color should be updated, which seems not quite elegant.

**Comment by tristen** [comment]
@wangzuo Ahhh thanks. I'll add something like this in!

**Comment by tristen** [comment]
Should be addressed with https://github.com/mapbox/react-colorpickr/pull/32
