### ISSUE TITLE
Css file won't apply to the component

### ISSUE THREAD

**Issue by Judith-coder** [mapbox/react-colorpickr#169]
Hello,
As indicated in the docs, I installed react-colorpickr and added the css link '<link href='react-colorpickr.css' rel='stylesheet' />' into the head of my index.html file but the style won't apply to the component ColorPicker.
The css file also seems empty (only .bg-tile and .gradient-hue mentionned).

From the docs, the link to the react-colorpickr.css leds to a 404.

Am I the only one facing this issue? How is it possible to fix this ?
Thanks.

**Comment by tristen** [comment]
Hi! Thanks for the flag about the bad link in the docs. That CSS file as you mentioned can be [found here](https://github.com/mapbox/react-colorpickr/blob/publisher-production/example/colorpickr.css) but the example [also uses a CSS framework](https://github.com/mapbox/react-colorpickr/blob/publisher-production/example/index.html#L7) here at Mapbox called [Assembly](https://github.com/mapbox/assembly). 

The colorpicker has [themeable overrides if you want to do your own thing too](https://github.com/mapbox/react-colorpickr#theme-objectkey-string-string). Hope that helps!
