### ISSUE TITLE
Display reset color instead of button

### ISSUE THREAD

**Issue by tristen** [mapbox/react-colorpickr#18]
Currently if the reset button is enabled, it jumps back to the previous color before. 

But it might be more useful if this were a swatch of the original color to measure contrast alongside a changed one:

![color-reset](https://cloud.githubusercontent.com/assets/61150/7839620/54fc05ee-0461-11e5-82cd-ee03a60481ff.gif)

Clicking on the original swatch would reset things. Thoughts @ajashton @nickidlugash ?

**Comment by nickidlugash** [comment]
@tristen :+1: :+1: :+1:

**Comment by ajashton** [comment]
Sure
