### ISSUE TITLE
Generate colorpicker bg in canvas

### ISSUE THREAD

**Issue by tmcw** [mapbox/react-colorpickr#24]
This would remove the manual step and make this configurable on the fly.

**Comment by tristen** [comment]
I don't know ... right now this is a deliciously small [data uri](https://github.com/mapbox/react-colorpickr/blob/65c31fe380ac9801ef964f64f30e53a0a6020709/react-colorpickr.css#L342).

**Comment by tmcw** [comment]
Sure, but it's existence makes react-colorpickr much harder to customize
