### ISSUE TITLE
More informative 'Reset color' button

### ISSUE THREAD

**Issue by heyitsgarrett** [mapbox/react-colorpickr#25]
The current/reset colors are identical when first opening up the pane, and it's not clear that one of them is designed to reset to the original value:

![image](https://cloud.githubusercontent.com/assets/200357/8580800/5db81412-2571-11e5-8eb7-086ad279819e.png)

 Consider adding icon or separating the two color squares (bad sketch below)

![image](https://cloud.githubusercontent.com/assets/200357/8580806/676d6eee-2571-11e5-83c7-f65b0848cdc7.png)

**Comment by tristen** [comment]
Yep - good call.

**Comment by tristen** [comment]
Agreed it's a little confusing at first. I'd like to keep the reset colour around though as this was implemented as a feature https://github.com/mapbox/react-colorpickr/issues/18

**Comment by tristen** [comment]
Captured changes that happened downstream. Let's work with inline labels for now.
