### ISSUE TITLE
rotated range input is buggy

### ISSUE THREAD

**Issue by samanpwbb** [mapbox/react-colorpickr#26]
the rotated range input sometimes doesn't work or is unresponsive, and covers up other elements on the page. Should un-rotate this guy and place it along the bottom:

<img width="368" alt="screen shot 2015-07-18 at 1 10 07 pm" src="https://cloud.githubusercontent.com/assets/108094/8762682/5ffb2734-2d4e-11e5-9a19-f33523a46856.png">

**Comment by tristen** [comment]
Closing as this was addressed in Studio and the unresponsiveness is not present on the demo page.

**Comment by samanpwbb** [comment]
:+1: I am unsure if rotation was the true cause of the problem in the first place.
