### ISSUE TITLE
Stop using eval under the hood

### ISSUE THREAD

**Issue by tmcw** [mapbox/react-colorpickr#27]
> 'unsafe-eval' ('store' via 'react-colorpicker' is being silly, Function('return this')(), could have other eval()/Function())

This is necessary to enable unsafe-eval rule in CSP downstream.

**Comment by tmcw** [comment]
Store is fixed upstream https://github.com/marcuswestin/store.js/commit/7c65e0a646c9c47432de8ae507e67efc548968ae but they haven't released a release with the fix yet.

**Comment by tmcw** [comment]
@tristen can you `npm owner add tmcw react-colorpickr` so I can push a release?

**Comment by tristen** [comment]
:ok_hand:
