### ISSUE TITLE
Alpha selector sometimes return int between 0-100 and sometimes returns float 0-1.0

### ISSUE THREAD

**Issue by kungfoolabs** [mapbox/react-colorpickr#43]
When using the alpha selector, it seems like there is a bug.

Using the slider will return alpha between 0-1.0, but when selecting a color, it will return an alpha between 0-100. It was a easy conditional on my side, but something that could be fixed I think.

**Comment by tristen** [comment]
@kungfoolabs selecting a color from the canvas, using the alpha slider or number input should all return a value from 0 - 1. Can you detail where this is not the case?

**Comment by tristen** [comment]
Closing. plz re-open if this is still being reproduced!
