### ISSUE TITLE
When dealing with a value on the very bottom of the color square, slider below it is buggy

### ISSUE THREAD

**Issue by lbud** [mapbox/react-colorpickr#54]
To reproduce:
1. Start at rgba(0,0,0,1) — the color dot on the square canvas is all the way at the bottom
2. Try to slide slider below it to change color

(be assured that the long period of nothing happening in this gif is me trying in vain to slide or click further down the slider)

![colorpickr](https://cloud.githubusercontent.com/assets/3170312/9923971/b2d99914-5caf-11e5-8d99-217191c81f38.gif)

**Comment by tristen** [comment]
I'm guessing this is a downstream issue from some custom CSS. The issue shouldn't be re-producable on the demo page: https://www.mapbox.com/react-colorpickr/example/ ?

**Comment by tristen** [comment]
Fixed with a z-index rule.
