### ISSUE TITLE
Drag events are generally "sticky" and unreliable

### ISSUE THREAD

**Issue by ajashton** [mapbox/react-colorpickr#55]
Using Chrome 45 on Ubuntu.

Examples:
- No matter what I do I can't drag the white circle all the way to the left or bottom of the square. It always gets stuck at a saturation or value of about 1-30.
- The hue slider will get stuck at 345 or 350 and I can't drag it any further to the right
- If I'm dragging the hue slider and my cursor leaves the very narrow rainbow track, the slider gets stuck in drag mode and will follow my cursor even after mouseup. I have to click again on the hue slider to stop it.

**Comment by tristen** [comment]
Are you replicating this on the [demo page](https://www.mapbox.com/react-colorpickr/example/)? Not seeing any of this behaviour there.

**Comment by ajashton** [comment]
Hm no that demo page works fine for me. Could be something specific to the implementation in Mapbox Studio.

**Comment by tristen** [comment]
Going to close this. the third issue should be addressed and if there's any issues that aren't reproducible from the demo - let's raise them downstream.
