### ISSUE TITLE
S and V mode color field controls are flipped

### ISSUE THREAD

**Issue by samanpwbb** [mapbox/react-colorpickr#58]
When S is active I control V:

<img width="438" alt="screen shot 2015-10-27 at 11 24 06 pm" src="https://cloud.githubusercontent.com/assets/108094/10779011/dbd83b28-7d01-11e5-9222-e3813c106a9c.png">

When V is active I control S:
<img width="458" alt="screen shot 2015-10-27 at 11 24 33 pm" src="https://cloud.githubusercontent.com/assets/108094/10779021/e6f8e318-7d01-11e5-9c5b-594a6e2e9a25.png">

---

Maybe this should be on a different ticket, but I think the mode switch interaction is poorly designed. It doesn't match user intention to change the functionality of the color field based on which input is active. User often wants to use the H version of the color field but manually input an S value. To see an example of a similar UI that is more user-friendly, check out Photoshop: it uses explicit toggles to switch modes. I'd even be in favor of locking the color field in Hue mode always – it's the most familiar and intuitive way to pick a color.

**Comment by tristen** [comment]
Agreed. I wanted to shortcut the action of changing mode & focusing the input in a single interaction. Not using the colorpicker on a regular basis I can see this not being a desired effect and it should be broken into a radio group next to each input similar to Photoshop. But yeah, let's split this off into it's own ticket.

**Comment by tristen** [comment]
Actually ... this is working as expected

**H mode:**  
- Slider adjusts Hue 
- XY control x axis adjusts Saturation
- XY control y axis adjusts Value

![h-mode](https://cloud.githubusercontent.com/assets/61150/10850727/91eac2ee-7efd-11e5-89f4-b22d91b44f71.gif)

**S mode:**  
- Slider adjusts Saturation 
- XY control x axis adjusts Hue
- XY control y axis adjusts Value

![s-mode](https://cloud.githubusercontent.com/assets/61150/10850742/a7563f5a-7efd-11e5-8c08-18ad207138dd.gif)

**V mode:**  
- Slider adjusts Value 
- XY control x axis adjusts Hue
- XY control y axis adjusts Saturation

![v-mode](https://cloud.githubusercontent.com/assets/61150/10850764/b7e63960-7efd-11e5-802e-5c650c93c297.gif)
