### ISSUE TITLE
Uses deprecated React.findDOMNode method

### ISSUE THREAD

**Issue by tmcw** [mapbox/react-colorpickr#65]

**Comment by tristen** [comment]
I think it's the `getDOMNode` method that's depreciated and `findDOMNode` should be used? https://facebook.github.io/react/blog/2015/10/07/react-v0.14.html

**Comment by tmcw** [comment]
Yeah, the reverse, sorry - typo

**Comment by tristen** [comment]
Cool - I think this has been cleaned up now.

**Comment by tmcw** [comment]
This isn't fixed

```
React.findDOMNode is deprecated. Please use ReactDOM.findDOMNode from require('react-dom') instead.
```
