### ISSUE TITLE
if more than one color picker on screen at a time, mode radio toggles are blank

### ISSUE THREAD

**Issue by samanpwbb** [mapbox/react-colorpickr#66]
Everything works, but mode toggles for the item lower in the dom are all always empty:

<img width="142" alt="screen shot 2015-12-09 at 10 23 36 pm" src="https://cloud.githubusercontent.com/assets/108094/11706084/9ddbf592-9ec3-11e5-8caa-402c76fe8333.png">

**Comment by tristen** [comment]
Hmm... I thought this would be scoped properly. Guessing the `name` property for radio inputs need a unique value.
