### ISSUE TITLE
.babelrc causes issues in other projects

### ISSUE THREAD

**Issue by samanpwbb** [mapbox/react-colorpickr#79]
Seeing this error when trying to require the 4.x.x versions of react-colorpickr. My app is using browserify with babelify.

`
ReferenceError: [BABEL] /Users/saman/work_repos/maki-icons/node_modules/react-colorpickr/dist/colorpickr.js: Unknown option: /Users/saman/work_repos/maki-icons/node_modules/react-colorpickr/.babelrc.presets while parsing file: /Users/saman/work_repos/maki-icons/node_modules/react-colorpickr/dist/colorpickr.js
`

https://github.com/mapbox/react-colorpickr/blob/mb-pages/.babelrc

If I add the following: 

```
[
    "babel-preset-es2015": "^6.3.13",
    "babel-preset-react": "^6.3.13",
    "babel-preset-stage-0": "^6.3.13",
]
```

as devDependencies in my project, the problem goes away, but that shouldn't' be required to use the colorpickr.

**Comment by tmcw** [comment]
We should remove the "browserify" field from package.json - it isn't necessary to transform this module in order to use it.
