### ISSUE TITLE
Peer Dependencies

### ISSUE THREAD

**Issue by brpsmith** [mapbox/react-colorpickr#90]
Any chance the peer dependencies are not correctly declared?  When attempting to build the module on Windows, it errors with a recent version of React, React-DOM (like 15.3.1) due to the current declaration not having >= for the specified version.  The strange thing is that the module builds fine on mac/apple/OSX.

**Comment by conorhastings** [comment]
@brpsmith Likely too strict and can be made `>=`. In terms of the errors on windows and not on OS X, any chance on windows you were using `npm@2` and `npm@3` on OS X. In `npm@2` failing to match a peer dependency will error, while in 3 it is just a warning

**Comment by brpsmith** [comment]
Thanks.  Definitely looks to be version related as I am using 2.15.8.  Will try npm@3 and see how it goes.
