### ISSUE TITLE
Once you select a channel there's no way out

### ISSUE THREAD

**Issue by davidtheclark** [mapbox/react-colorpickr#93]
If I'm in RGB mode and select the R channel, so R stays constant while the others change, I don't think there's a way to get out of that mode — to deselect the R channel and once again change the whole color at once.

Am I missing something? Or is this a legit bug?

cc @mapbox/appbox

**Comment by samanpwbb** [comment]
You can change the color channel by clicking on the radio button next to the toggle. A channel must always be selected. The default channel is H of HSV.
